Flight_Board/config/routes.rb
Rails.application.routes.draw do
  resources :flight_routes do
    resources :flights
  end
  get "/users/new", controller: "users", action: "new"

  post "/users", controller: "users", action: "create"

  root controller: "flight_routes", action: "index"

end

Flight_Board/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Flight_Board/app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :flight_routes
end

Flight_Board/app/models/flight_route.rb
class FlightRoute < ApplicationRecord
  has_many :flights
end

Flight_Board/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

Flight_Board/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    if session[:current_user_id]
      @current_user ||= User.find_by(id: session[:current_user_id])
    end
  end
end

Flight_Board/app/controllers/flight_routes_controller.rb
class FlightRoutesController < ApplicationController
  before_action :set_flight_route, only: [:show, :edit, :update, :destroy]

  # GET /flight_routes
  def index
    @flight_routes = FlightRoute.all
  end

  # GET /flight_routes/1
  def show
  end

  # GET /flight_routes/new
  def new
    @flight_route = FlightRoute.new
  end

  # GET /flight_routes/1/edit
  def edit
  end

  # POST /flight_routes
  def create
    @flight_route = FlightRoute.new(flight_route_params)

    if @flight_route.save
      redirect_to @flight_route, notice: 'Flight route was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /flight_routes/1
  def update
    if @flight_route.update(flight_route_params)
      redirect_to @flight_route, notice: 'Flight route was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /flight_routes/1
  def destroy
    @flight_route.destroy
    redirect_to flight_routes_url, notice: 'Flight route was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight_route
      @flight_route = FlightRoute.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def flight_route_params
      params.require(:flight_route).permit(:destination, :origin, :distance)
    end
end

Flight_Board/app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  def index
    @flights = Flight.all
  end

  def show
  end

  def new
    @flight_route = FlightRoute.find(params[:flight_route_id])
    @flight = @flight_route.flights.new
  end

  def create

    @flight_route = FlightRoute.find(params[:flight_route_id])
    @flight = @flight_route.flights.new(flight_params)
    binding.pry

    if @flight.save
      redirect_to flight_routes_path, notice: "Flight has been created."
    else
      render "new"
    end
  end


  private

  def flight_params
    params.require(:flight).permit(:name, :flight_routes_id, :number_of_passengers, :arrived, :stocked, :clean)
  end

  def set_flight
    @flight = Flight.find(params[:id])
  end
end

Flight_Board/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if current_user
      redirect_to
    else
      render "new"
    end
  end

  def create
  @user = User.find_by(name: params["name"])
  if @user && @user.password == params[:password]
    session[:current_user_id] = @user.id
    redirect_to flight_routes_path
  else
    flash[:error] = "Please make sure you have created a profile"
    redirect_to new_sessions_path
  end
end
end

Flight_Board/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to flight_routes_path
    else
      render "new"
    end
  end

  private

  def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

Flight_Board/app/helpers/application_helper.rb
module ApplicationHelper
end

Flight_Board/app/helpers/flight_routes_helper.rb
module FlightRoutesHelper
end

Flight_Board/app/helpers/flights_helper.rb
module FlightsHelper
end

Flight_Board/app/helpers/sessions_helper.rb
module SessionsHelper
end

Flight_Board/app/helpers/users_helper.rb
module UsersHelper
end

Flight_Board/app/views/flight_routes/_form.html.erb
<%= form_for(flight_route) do |f| %>
  <% if flight_route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight_route.errors.count, "error") %> prohibited this flight_route from being saved:</h2>

      <ul>
      <% flight_route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :destination %>
    <%= f.text_field :destination %>
  </div>

  <div class="field">
    <%= f.label :origin %>
    <%= f.text_field :origin %>
  </div>

  <div class="field">
    <%= f.label :distance %>
    <%= f.number_field :distance %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Flight_Board/app/views/flight_routes/edit.html.erb
<h1>Editing Flight Route</h1>

<%= render 'form', flight_route: @flight_route %>

<%= link_to 'Show', @flight_route %> |
<%= link_to 'Back', flight_routes_path %>

Flight_Board/app/views/flight_routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flight Routes</h1>

<table>
  <thead>
    <tr>
      <th>Destination</th>
      <th>Origin</th>
      <th>Distance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flight_routes.each do |flight_route| %>
      <tr>
        <td><%= flight_route.destination %></td>
        <td><%= flight_route.origin %></td>
        <td><%= flight_route.distance %></td>
        <td><%= link_to 'Show', flight_route %></td>
        <td><%= link_to 'Edit', edit_flight_route_path(flight_route) %></td>
        <td><%= link_to 'Destroy', flight_route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to "Add flight", new_flight_route_flight_path(flight_route) %></td>
        <td><%= link_to "View flights for this route", flight_route_flights_path(flight_route) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight Route', new_flight_route_path %>

Flight_Board/app/views/flight_routes/new.html.erb
<h1>New Flight Route</h1>

<%= render 'form', flight_route: @flight_route %>

<%= link_to 'Back', flight_routes_path %>

Flight_Board/app/views/flight_routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Destination:</strong>
  <%= @flight_route.destination %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @flight_route.origin %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @flight_route.distance %>
</p>

<%= link_to 'Edit', edit_flight_route_path(@flight_route) %> |
<%= link_to 'Back', flight_routes_path %>

Flight_Board/app/views/flights/_form.html.erb
<h1>Create flight for route from <%=@flight_route.origin %> to <%= @flight_route.destination %></h1>
<%= form_for [@flight_route, @flight] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :number_of_passengers %>
  <%= f.number_field :number_of_passengers %>

  <%= f.label :arrived %>
  <%= f.check_box :arrived, {}, true, false %>

  <%= f.label :clean %>
  <%= f.check_box :clean, {}, true, false %>

  <%= f.label :stocked %>
  <%= f.check_box :stocked, {}, true, false %>

  <%= f.submit %>

<% end %>

Flight_Board/app/views/flights/index.html.erb
<h1>Flights</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of Passengers</th>
      <th>Route</th>
      <th>Arrived</th>
      <th>Cleaned</th>
      <th>Stocked</th>
    </tr>
  </thead>

  <tbody>
    <%= @flights.each do |flight| %>
    <td><%= flight.name %></td>
        <td><%= flight.number_of_passengers %></td>
        <td><%= flight.arrived %></td>
        <td><%= flight.clean %></td>
        <td><%= flight.stocked %></td>
    <% end %>
  </tbody>
</table>

Flight_Board/app/views/flights/new.html.erb
<%= render "form" %>

Flight_Board/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <% if current_user %>
      <%= current_user&.username %> |
      <%= link_to "logout", "/sessions", method: "delete" %>
    <% else %>
      <%= link_to "Create User", "/users/new" %> |
      <%= link_to "Sign In", "/sessions/new" %>
    <% end %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

Flight_Board/app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= @user.errors.full_messages.join("") %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>

<% end %>